# Generated by Django 4.1.7 on 2023-02-26 11:24

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="detailed_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default=django.utils.timezone.now,
                help_text="Подробное описание выполненной работы",
                verbose_name="Подробное описание",
            ),
            preserve_default=False,
        ),
    ]
